[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
candl = "JDqvbHqaL1W57YALJnY1Lyyi6Ai5aFMaNi1mzYATTYAa"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
